wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.0
    start_time: 1719079677.633217
    t:
      1:
      - 55
      2:
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.0
      5: 0.13.11
      8:
      - 1
      - 3
      - 5
