wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.0
    start_time: 1719079842.163733
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 13
      - 23
      4: 3.10.0
      5: 0.13.11
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: resnet34
batch_size:
  desc: null
  value: 64
classes:
  desc: null
  value:
  - negative
  - positive
cuda_device_count:
  desc: null
  value: 0
epochs:
  desc: null
  value: 2
l2_regularization:
  desc: null
  value: 0.0005
learning_rate:
  desc: null
  value: 0.01
lr_cooling_factor:
  desc: null
  value: 0.7
lr_update_interval:
  desc: null
  value: 10
model_save_path:
  desc: null
  value: \\ban-files-02\Groups\EI Monitoring\Amphibian Acoustic Classifier\Analysis\ETL\model_training_checkpoints
mps_available:
  desc: null
  value: false
num_workers:
  desc: null
  value: 4
opensoundscape_version:
  desc: null
  value: 0.10.1
optimizer_cls:
  desc: null
  value: torch.optim.sgd.SGD
sample_duration:
  desc: null
  value: 3
sample_shape:
  desc: null
  value:
  - 224
  - 224
  - 3
single_target:
  desc: null
  value: false
