wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719080162
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 13
      - 23
      4: 3.10.0
      5: 0.17.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
architecture:
  desc: null
  value: resnet34
sample_duration:
  desc: null
  value: 3
cuda_device_count:
  desc: null
  value: 0
mps_available:
  desc: null
  value: false
classes:
  desc: null
  value:
  - negative
  - positive
single_target:
  desc: null
  value: false
opensoundscape_version:
  desc: null
  value: 0.10.1
l2_regularization:
  desc: null
  value: 0.0005
learning_rate:
  desc: null
  value: 0.01
sample_shape:
  desc: null
  value:
  - 224
  - 224
  - 3
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 4
lr_update_interval:
  desc: null
  value: 10
lr_cooling_factor:
  desc: null
  value: 0.7
optimizer_cls:
  desc: null
  value: torch.optim.sgd.SGD
model_save_path:
  desc: null
  value: \\ban-files-02\Groups\EI Monitoring\Amphibian Acoustic Classifier\Analysis\ETL\model_training_checkpoints
